FROM kpsr-thirdparties:ZMQ as thirdparties

# Compile docker
FROM kpsr-core:sys_dep_ubuntu_18.04 as compile_docker

ARG BUILD_ID
LABEL kpsr-core=compile_docker
LABEL BUILD_ID=${BUILD_ID}
LABEL method=ZMQ

WORKDIR /opt

# Internal dependencies
COPY --from=thirdparties /opt/klepsydra/thirdparties/ /opt/klepsydra/thirdparties/
COPY --from=thirdparties /usr/local/include/yaml-cpp/ /usr/local/include/yaml-cpp/
COPY --from=thirdparties /usr/local/lib/cmake/yaml-cpp/ /usr/local/lib/cmake/yaml-cpp/
COPY --from=thirdparties /usr/local/lib/libyaml* /usr/local/lib/

# Klepsydra
COPY . kpsr-core

RUN cd kpsr-core \
    && git submodule update --init \
    && mkdir build \
    && cd build \
    && cmake -DKPSR_WITH_DOXYGEN=true -DKPSR_WITH_DDS=false -DKPSR_WITH_ZMQ=true\
       -DKPSR_TEST_PERFORMANCE=true -DKPSR_WITH_SOCKET=true -DKPSR_WITH_YAML=true\
       -DKPSR_WITH_CODE_METRICS=true -DCMAKE_PREFIX_PATH=/opt/klepsydra/thirdparties\
       -DCMAKE_BUILD_TYPE=Debug ..\
    && make
