ARG test_image

# Install
FROM $test_image as install_docker
LABEL kpsr-core=install_docker
RUN cd kpsr-core/build/ && make install

# Clean the image
FROM ubuntu:18.04

COPY --from=install_docker /usr/local/include/klepsydra/ /usr/local/include/klepsydra/
COPY --from=install_docker /usr/local/include/kpsr_3parties/ /usr/local/include/kpsr_3parties/
COPY --from=install_docker /usr/local/lib/cmake/klepsydra/ /usr/local/lib/cmake/klepsydra/
COPY --from=install_docker /usr/local/lib/libkpsr* /usr/local/lib/
COPY --from=install_docker /root/ /root/

# Original files.
COPY --from=install_docker /opt/klepsydra /opt/klepsydra 

# Add thirdparties to default path.
RUN apt update && apt install rsync -y && rsync -a /opt/klepsydra/thirdparties/ /usr/

WORKDIR /opt/
