FROM kpsr-thirdparties:ZMQ as compile_docker

ARG BUILD_ID
LABEL kpsr-core=compile_docker
LABEL BUILD_ID=${BUILD_ID}
LABEL method=ZMQ

WORKDIR /opt

# Klepsydra
COPY . kpsr-core

RUN cd kpsr-core \
    && git submodule update --init \
    && mkdir build \
    && cd build \
    && cmake -DKPSR_WITH_DOXYGEN=true -DKPSR_WITH_ZMQ=true \
             -DKPSR_TEST_PERFORMANCE=true -DKPSR_WITH_SOCKET=true -DKPSR_WITH_CODE_METRICS=true \
             -DCMAKE_PREFIX_PATH=/opt/klepsydra/thirdparties -DCMAKE_BUILD_TYPE=Debug -DCSP_HOME=/opt/libcsp/ \
             -DKPSR_WITH_CSP=true -DKPSR_WITH_CSP_ZMQ=true -DKPSR_WITH_CSP_CAN=true .. \
    && make
