
FROM ros:melodic-ros-core-bionic

ARG YAMLCPPVERSION="yaml-cpp-0.6.0"

ENV TZ 'Europe/Madrid'
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
    apt-get -y install \
    build-essential \
    cmake \
    cppcheck \
    doxygen \
    doxygen-doc \
    gcovr \
    graphviz \
    lcov \
    libyaml-cpp-dev \
    libzmqpp-dev \
    locales \
    locales-all \
    ninja-build \
    pkg-config \
    python3-pip \
    software-properties-common \
    tzdata \
    wget && \
    ## Add git and cmake repositories and python repositories to install newer versions
    add-apt-repository ppa:git-core/ppa && \
    add-apt-repository ppa:deadsnakes/ppa && \
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null && \
    echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ xenial main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null && \
    # Install latest stable git and cmake
    apt-get update && \
    apt-get -y install git \
    cmake-data=3.15.0-0kitware1 \
    cmake=3.15.0-0kitware1 && \
    ## Cleanup
    apt-get -y autoremove && \
    apt-get -y clean && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    rm -rf /var/lib/apt/lists/* /usr/share/man/* /var/cache/man/* /usr/share/doc/*

RUN git clone https://github.com/google/benchmark.git && \
    cd benchmark && \
    git checkout v1.6.0 && \
    mkdir build && cd build && \
    cmake --parallel ${nproc} -DBENCHMARK_DOWNLOAD_DEPENDENCIES=on -DCMAKE_BUILD_TYPE=Release ../ && \
    make install && \
    cd ../../ && \
    rm -rf benchmark
