# Compile docker
FROM kpsr-core:sys_dep_ubuntu_18.04 as compile_docker

ARG BUILD_ID
LABEL kpsr-core=compile_docker
LABEL BUILD_ID=${BUILD_ID}
LABEL method=Vanilla

WORKDIR /opt

# Klepsydra
COPY kpsr-core kpsr-core

RUN cd kpsr-core \
    && git submodule update --init \
    && mkdir build \
    && cd build \
    && cmake -DKPSR_WITH_DOXYGEN=true -DKPSR_WITH_DDS=false -DKPSR_WITH_ZMQ=false\
       -DKPSR_TEST_PERFORMANCE=true -DKPSR_WITH_SOCKET=true -DKPSR_WITH_YAML=false\
       -DKPSR_WITH_CODE_METRICS=true -DCMAKE_PREFIX_PATH=/opt/klepsydra/thirdparties\
       -DCMAKE_BUILD_TYPE=Debug ..\
    && make

# Install
FROM compile_docker as install_docker
LABEL kpsr-core=install_docker
RUN cd kpsr-core/build/ && make install

# Clean the image
FROM ubuntu:18.04

COPY --from=install_docker /usr/local/include/klepsydra/ /usr/local/include/klepsydra/
COPY --from=install_docker /usr/local/lib/cmake/klepsydra/ /usr/local/lib/cmake/klepsydra/
COPY --from=install_docker /usr/local/lib/libkpsr* /usr/local/lib/

WORKDIR /opt/
