ARG test_image

FROM $test_image as install_docker
# Install
RUN cd /kpsr-ros \
    && . /opt/ros/kinetic/setup.sh \
    && catkin_make install

# Clean the image
FROM kpsr-thirdparties:sys_dep_ros_ubuntu_16.04

COPY --from=install_docker /usr/local/include/klepsydra/ /usr/local/include/klepsydra/
COPY --from=install_docker /usr/local/include/kpsr_3parties/ /usr/local/include/kpsr_3parties/
COPY --from=install_docker /usr/local/lib/cmake/klepsydra/ /usr/local/lib/cmake/klepsydra/
COPY --from=install_docker /usr/local/lib/libkpsr* /usr/local/lib/
COPY --from=install_docker /opt/ /opt/
COPY --from=install_docker /kpsr-ros/ /kpsr-ros/
COPY --from=install_docker /root/ /root/

WORKDIR /opt/
