FROM kpsr-thirdparties:ROS as thirdparties

FROM ubuntu:18.04 AS builder

# System Dependencies.

RUN apt update && apt-get install libssl-dev libcurl4-gnutls-dev build-essential git cmake python cppcheck doxygen python3-pip gcovr lcov curl -y --fix-missing
RUN curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh && bash nodesource_setup.sh && apt install nodejs

# Internal dependencies
COPY --from=thirdparties /opt/ /opt/
COPY --from=thirdparties /usr/ /usr/

# Install pip packages (Optimizing cache building)
RUN npm install -g moxygen

WORKDIR /opt

# Klepsydra
COPY . kpsr-core

RUN cd kpsr-core \
    && git submodule update --init \
    && mkdir build \
    && cd build \
    && cmake -DKPSR_WITH_DOXYGEN=true -DKPSR_WITH_DDS=false -DKPSR_WITH_ZMQ=false\
       -DKPSR_TEST_PERFORMANCE=true -DKPSR_WITH_SOCKET=true -DKPSR_WITH_YAML=true\
       -DKPSR_WITH_CODE_METRICS=true -DCMAKE_PREFIX_PATH=/opt/klepsydra/thirdparties\
       -DCMAKE_BUILD_TYPE=Debug ..\
    && make \
    && bash ../kpsr-build/scripts/make_cppcheck.sh \
    && make test_coverage_cobertura ARGS="-V" \
    && make doc \
    && make install
RUN cd ../../ \
    && /opt/ros/melodic/setup.sh \
    && mkdir -p kpsr-ros/src \
    && cd kpsr-ros/src \
    && catkin_init_workspace \
    && ln -s ../../kpsr-core/core/modules/ros_mdlw/kpsr_ros_core . \
    && ln -s ../../kpsr-core/serialization/modules/ros_mdlw/kpsr_ros_serialization . \
    && ln -s ../../kpsr-core/code_generator/cpp_testing/tests/kpsr_ros_codegen . \
    && cd .. \
    && catkin_make -DCMAKE_INSTALL_PREFIX=/opt/klepsydra \
    && catkin_make tests \
    && catkin_make install

ARG BUILD_ID
LABEL kpsr-core=builder
LABEL BUILD_ID=${BUILD_ID}

FROM ubuntu:18.04

COPY --from=builder /usr/local/include/klepsydra/ /usr/local/include/klepsydra/
COPY --from=builder /usr/local/lib/cmake/klepsydra/ /usr/local/lib/cmake/klepsydra/
COPY --from=builder /usr/local/lib/libkpsr* /usr/local/lib/
COPY --from=builder /opt/klepsydra/ /opt/klepsydra/

WORKDIR /opt/

