ARG test_image

# Install
FROM $test_image as compile_ros
LABEL kpsr-core=compile_ros

RUN cd kpsr-core/build/ && make install

RUN cd / \
    && . /opt/ros/melodic/setup.sh \
    && mkdir -p kpsr-ros/src \
    && cd kpsr-ros/src \
    && catkin_init_workspace \
    && ln -s /opt/kpsr-core/core/modules/ros_mdlw/kpsr_ros_core . \
    && ln -s /opt/kpsr-core/serialization/modules/ros_mdlw/kpsr_ros_serialization . \
    && ln -s /opt/kpsr-core/code_generator/cpp_testing/tests/kpsr_ros_codegen . \
    && cd .. \
    && catkin_make -DCMAKE_INSTALL_PREFIX=/opt/klepsydra \
    && catkin_make tests
