ARG test_image

FROM $test_image as install_docker
# Install
RUN cd /kpsr-ros \
    && . /opt/ros/melodic/setup.sh \
    && catkin_make install

# Clean the image
FROM ubuntu:18.04

COPY --from=install_docker /usr/local/include/klepsydra/ /usr/local/include/klepsydra/
COPY --from=install_docker /usr/local/lib/cmake/klepsydra/ /usr/local/lib/cmake/klepsydra/
COPY --from=install_docker /usr/local/lib/libkpsr* /usr/local/lib/
COPY --from=install_docker /root/ /root/

WORKDIR /opt/
