FROM ubuntu:20.04

ARG YAMLCPPVERSION="yaml-cpp-0.6.0"

ENV TZ 'Europe/Madrid'
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
    apt-get -y install \
    build-essential \
    cmake \
    cppcheck \
    doxygen \
    doxygen-doc \
    gcovr \
    git \
    graphviz \
    lcov \
    locales \
    locales-all \
    pkg-config \
    python3-pip \
    tzdata \
    ninja-build \
    && \
    ## Cleanup
    apt-get -y autoremove && \
    apt-get -y clean && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    rm -rf /var/lib/apt/lists/* /usr/share/man/* /var/cache/man/* /usr/share/doc/*

RUN git clone https://github.com/jbeder/yaml-cpp && cd yaml-cpp && git checkout ${YAMLCPPVERSION} && \
    mkdir build && cd build && cmake -DYAML_BUILD_SHARED_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON ../ && make -j ${nproc} && make install && \
    cd ../../ && rm -rf yaml-cpp
