FROM ubuntu:20.04

ENV TZ 'Europe/Madrid'
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
    apt-get -y install \
    build-essential \
    cmake \
    cppcheck \
    doxygen \
    doxygen-doc \
    gcovr \
    git \
    graphviz \
    lcov \
    locales \
    locales-all \
    pkg-config \
    python3-pip \
    tzdata \
    ninja-build \
    && \
    ## Cleanup
    apt-get -y autoremove && \
    apt-get -y clean && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    rm -rf /var/lib/apt/lists/* /usr/share/man/* /var/cache/man/* /usr/share/doc/*

RUN git clone https://github.com/google/benchmark.git && \
    cd benchmark && \
    git checkout v1.6.0 && \
    mkdir build && cd build && \
    cmake --parallel ${nproc} -DBENCHMARK_DOWNLOAD_DEPENDENCIES=on -DCMAKE_BUILD_TYPE=Release ../ && \
    make install && \
    cd ../../ && \
    rm -rf benchmark
