name: ROS

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  noetic-x86:
    name: Noetic Ubuntu 20.04
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: noetic
    timeout-minutes: 20
    container:
      image: 337955887028.dkr.ecr.us-east-2.amazonaws.com/kpsr-docker-registry/github/kpsr-core:Noetic_1.0.1
      credentials:
        username: AWS
        password: ${{ secrets.ECR_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/build
          cd ${GITHUB_WORKSPACE}/build
          cmake -DKPSR_WITH_DOXYGEN=true -DKPSR_WITH_DDS=false -DKPSR_WITH_ZMQ=false -DKPSR_TEST_PERFORMANCE=true -DKPSR_WITH_SOCKET=true -DKPSR_WITH_YAML=true -DKPSR_WITH_CODE_METRICS=true -DCMAKE_BUILD_TYPE=Debug ../
          make -j$(nproc)

      - name: Test
        run: |
          cd ${GITHUB_WORKSPACE}/build
          make test ARGS="--gtest_shuffle"

      - name: Install
        run: |
          cd ${GITHUB_WORKSPACE}/build
          make install

      - name: Create ROS environment
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          mkdir -p /kpsr-ros/src/build
          cd /kpsr-ros/src
          catkin_init_workspace
          ln -s ${GITHUB_WORKSPACE}/core/modules/ros_mdlw/kpsr_ros_core . 
          ln -s ${GITHUB_WORKSPACE}/serialization/modules/ros_mdlw/kpsr_ros_serialization .
          ln -s ${GITHUB_WORKSPACE}/code_generator/cpp_testing/tests/kpsr_ros_codegen .

      - name: Build ROS
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd /kpsr-ros/src/build
          cmake ../ -DCMAKE_INSTALL_PREFIX=../install -DCATKIN_DEVEL_PREFIX=../devel
          make -j$(nproc)

      - name: Test ROS
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd /kpsr-ros/src/build
          make tests
          roscore &
          make test

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: noetic-logs
          path: |
            build/Testing/Temporary
            build/code_generator/kpsr_codegen/build_cpptesting/Testing/Temporary
            /kpsr-ros/src/build/Testing/Temporary
            /kpsr-ros/src/build/test_results

  melodic-x86:
    name: Melodic Ubuntu 18.04
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: melodic
    timeout-minutes: 20
    container:
      image: 337955887028.dkr.ecr.us-east-2.amazonaws.com/kpsr-docker-registry/github/kpsr-core:Melodic_1.0.1
      credentials:
        username: AWS
        password: ${{ secrets.ECR_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/build
          cd ${GITHUB_WORKSPACE}/build
          cmake -DKPSR_WITH_DOXYGEN=true -DKPSR_WITH_DDS=false -DKPSR_WITH_ZMQ=false -DKPSR_TEST_PERFORMANCE=true -DKPSR_WITH_SOCKET=true -DKPSR_WITH_YAML=true -DKPSR_WITH_CODE_METRICS=true -DCMAKE_BUILD_TYPE=Debug ../
          make -j$(nproc)

      - name: Test
        run: |
          cd ${GITHUB_WORKSPACE}/build
          make test ARGS="--gtest_shuffle"

      - name: Install
        run: |
          cd ${GITHUB_WORKSPACE}/build
          make install

      - name: Create ROS environment
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          mkdir -p /kpsr-ros/src/build
          cd /kpsr-ros/src
          catkin_init_workspace
          ln -s ${GITHUB_WORKSPACE}/core/modules/ros_mdlw/kpsr_ros_core . 
          ln -s ${GITHUB_WORKSPACE}/serialization/modules/ros_mdlw/kpsr_ros_serialization .
          ln -s ${GITHUB_WORKSPACE}/code_generator/cpp_testing/tests/kpsr_ros_codegen .

      - name: Build ROS
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd /kpsr-ros/src/build
          cmake ../ -DCMAKE_INSTALL_PREFIX=../install -DCATKIN_DEVEL_PREFIX=../devel
          make -j$(nproc)

      - name: Test ROS
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd /kpsr-ros/src/build
          make tests
          roscore &
          make test

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: melodic-logs
          path: |
            build/Testing/Temporary
            build/code_generator/kpsr_codegen/build_cpptesting/Testing/Temporary
            /kpsr-ros/src/build/Testing/Temporary
            /kpsr-ros/src/build/test_results

  kinetic-x86:
    name: Kinetic Ubuntu 16.04
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      ROS_DISTRO: kinetic
    container:
      image: 337955887028.dkr.ecr.us-east-2.amazonaws.com/kpsr-docker-registry/github/kpsr-core:Kinetic_1.0.1
      credentials:
        username: AWS
        password: ${{ secrets.ECR_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/build
          cd ${GITHUB_WORKSPACE}/build
          cmake -DKPSR_WITH_DOXYGEN=true -DKPSR_WITH_DDS=false -DKPSR_WITH_ZMQ=false -DKPSR_TEST_PERFORMANCE=true -DKPSR_WITH_SOCKET=true -DKPSR_WITH_YAML=true -DKPSR_WITH_CODE_METRICS=true -DCMAKE_BUILD_TYPE=Debug ../
          make -j$(nproc)

      - name: Test
        run: |
          cd ${GITHUB_WORKSPACE}/build
          make test ARGS="--gtest_shuffle"

      - name: Install
        run: |
          cd ${GITHUB_WORKSPACE}/build
          make install

      - name: Create ROS environment
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          mkdir -p /kpsr-ros/src/build
          cd /kpsr-ros/src
          catkin_init_workspace
          ln -s ${GITHUB_WORKSPACE}/core/modules/ros_mdlw/kpsr_ros_core . 
          ln -s ${GITHUB_WORKSPACE}/serialization/modules/ros_mdlw/kpsr_ros_serialization .
          ln -s ${GITHUB_WORKSPACE}/code_generator/cpp_testing/tests/kpsr_ros_codegen .

      - name: Build ROS
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd /kpsr-ros/src/build
          cmake ../ -DCMAKE_INSTALL_PREFIX=../install -DCATKIN_DEVEL_PREFIX=../devel
          make -j$(nproc)

      - name: Test ROS
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd /kpsr-ros/src/build
          make tests
          roscore &
          make test

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: kinetic-logs
          path: |
            build/Testing/Temporary
            build/code_generator/kpsr_codegen/build_cpptesting/Testing/Temporary
            /kpsr-ros/src/build/Testing/Temporary
            /kpsr-ros/src/build/test_results
